# Microéconomie 2 { .unnumbered }

Notes du cours de microéconomie 2 en licence 2 à l'université Paris 8, donné par Hela Maafi, Antoine Terracol et Elias Bouacida.  
Ce dépôt contient les notes de cours ainsi que les corrigés des exercices.
Ces notes ont été réalisées à partir des notes manuscrites d'Antoine Terracol et originellement tapées par Elias Bouacida. 
Les notes actuelles sont le travail combiné des trois enseignants.

## Thèmes

Les principaux thèmes abordés dans ce cours sont les suivants :

- structures de marché ;
- pouvoir de marché ;
- principes de tarification ;
- comportements stratégiques ;
- problèmes d'information.

L'idée générale est de dépasser le cadre de la concurrence pure et parfaite et de se rapprocher un peu du *monde réel* en levant certaines hypothèses de la concurrence pure et parfaite.

## Bibliographie

Le cours ne nécessite pas de se référer à un manuel. 
Néanmoins, pour ceux qui souhaitent des éclairages différents sur les notions abordés, voici quelques références utiles:

- @varian2015 *Introduction à la microéconomie*
- @varian2008 *Analyse Microéconomique*
- @pindyck2012 *Microéconomie*
- @jeleva2014 *Microéconomie*

Et enfin une référence avancée, pour ceux qui cherchent les fondements mathématiques (en anglais) :

- @mas1995 *Microeconomic Theory*

## Plan du cours

1. Le marché en concurrence pure et parfaite
2. Monopoles
    - Monopoles simples
    - Monopoles discriminants
    - Pouvoir de marché et principes de tarification
3. Oligopoles
    - Duopoles à la Cournot
    - Duopoles à la Stackelberg
    - Collusion et cartel (maintenant hors programme)





